### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by duckandflea** [pootle/pisteppers#5]
I can't get the webapp to run successfully. I have copied a modified one of the motor json files so I can change the pins, and that works successfully then I seem to get this AttributeError... 
I was also having trouble when I passed the settings file using -s so I just put it direct into the config_full.py file.

```
08:16    INFO (1893)  MainThread  watchables.log: logging level is loglvls.INFO
08:16    INFO (1893)  MainThread  watchables.log: app settings loaded from file motorpairA4988.json
08:16    INFO (1893)  MainThread  watchables.log: drive enable (pin 2) set for output, initialised to disable (1)
08:16    INFO (1893)  MainThread  watchables.log: direction (pin 18) set for output, initialised to F (0)
08:16    INFO (1893)  MainThread  watchables.log: step (pin 15) set for output, initialised to 0 (0)
08:16    INFO (1893)  MainThread  watchables.log: usl 0 (gpio 03) (pin 3) set for output, initialised to 0 (0)
08:16    INFO (1893)  MainThread  watchables.log: usl 1 (gpio 04) (pin 4) set for output, initialised to 0 (0)
08:16    INFO (1893)  MainThread  watchables.log: usl 2 (gpio 14) (pin 14) set for output, initialised to 0 (0)
08:16    INFO (1893)  MainThread  watchables.log: microstep pins [{'pinno': 3}, {'pinno': 4}, {'pinno': 14}] created
08:16    INFO (1893)  MainThread  watchables.log: starting motor a4988m1 thread stepper using class webstepchipmotor
08:16    INFO (1893)  MainThread  watchables.log: drive enable (pin 10) set for output, initialised to disable (1)
08:16    INFO (1893)  MainThread  watchables.log: direction (pin 7) set for output, initialised to F (0)
08:16    INFO (1893)  MainThread  watchables.log: step (pin 11) set for output, initialised to 0 (0)
08:16    INFO (1893)  MainThread  watchables.log: usl 0 (gpio 25) (pin 25) set for output, initialised to 0 (0)
08:16    INFO (1893)  MainThread  watchables.log: usl 1 (gpio 09) (pin 9) set for output, initialised to 0 (0)
08:16    INFO (1893)  MainThread  watchables.log: usl 2 (gpio 08) (pin 8) set for output, initialised to 0 (0)
08:16    INFO (1893)  MainThread  watchables.log: microstep pins [{'pinno': 25}, {'pinno': 9}, {'pinno': 8}] created
08:16    INFO (1893)  MainThread  watchables.log: starting motor a4988m2 thread stepper using class webstepchipmotor
<pootlestuff.watchables.enumWatch object at 0xb56b2730>
Traceback (most recent call last):
  File "app.py", line 29, in <module>
    webserv.runmain()
  File "/usr/local/lib/python3.7/dist-packages/pootlestuff/webserv.py", line 77, in runmain
    config=configmodule.setup(settings=args.settings if hasattr(args,'settings') else None)
  File "/home/pi/pisteppers/config_full.py", line 44, in setup
    app1 = stepperweb.webapp(value=settingsfile if settings is None else settings)
  File "/home/pi/pisteppers/stepperweb.py", line 127, in __init__
    multimotor.__init__(self, loglvl=wv.loglvls.INFO, **kwargs)
  File "/home/pi/pisteppers/steppergroup.py", line 46, in __init__
    print(self.alt_target)
AttributeError: 'webapp' object has no attribute 'alt_target'
```

**Comment by pootle** [comment]
I haven't got a test rig at the moment, but just comment out that line and see what happens.

**Comment by duckandflea** [comment]
> I haven't got a test rig at the moment, but just comment out that line and see what happens.

Thanks. Is it line 46 in steppergroup.py that I comment out? Or one of the other ones?

**Comment by duckandflea** [comment]
You can probably tell I know nothing. Seems like an obvious thing to try! Commenting out the print line ( line 46 in steppergroup.py) worked though. Thanks.
